import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en" | "fon" | "es" | "de" | "yo";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.fr;
}

const translations = {
  fr: {
    nav: {
      home: "Accueil",
      about: "À Propos",
      skills: "Compétences",
      projects: "Projets",
      services: "Services",
      blog: "Blog",
      contact: "Contact",
      cv: "Mon CV",
    },
    hero: {
      badge: "Disponible pour missions remote",
      name: "Eldo-Moréo",
      title: "Architecte Backend · SaaS · Automatisation",
      description:
        "Je conçois des systèmes backend robustes et scalables pour transformer vos idées produit en solutions rentables. Sécurité des données, optimisation des coûts serveur, architecture modulaire — pour itérer vite sans tout casser.",
      cta1: "Voir mes projets",
      cta2: "Me contacter",
      viewCV: "Mon CV",
      downloadCV: "Télécharger CV",
      stat1label: "Ans d'expérience backend",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL en production",
      stat2label: "Projets SaaS livrés",
      stat2sub: "Multi-tenancy, APIs REST, systèmes d'abonnement",
      stat3label: "Remote · International",
      stat3sub: "Disponible Afrique de l'Ouest & international",
    },
    about: {
      title: "À Propos",
      intro:
        "Full-Stack Developer spécialisé dans la conception de SaaS et l'automatisation. Je construis des infrastructures backend pensées pour la croissance.",
      values: "Mes Valeurs",
      learning: "Apprentissage continu",
      learningDesc:
        "Toujours en veille sur les architectures et patterns backend",
      flexibility: "Pragmatisme",
      flexibilityDesc:
        "Solutions simples, maintenables, qui tiennent en production",
      patience: "Rigueur",
      patienceDesc: "Approche méthodique : architecture d'abord, code ensuite",
      travel: "Vision produit",
      travelDesc: "Je pense business autant que technique",
    },
    skills: {
      title: "Compétences Techniques",
      dataScience: "Data & Automatisation",
      webDev: "Backend & Développement Web",
      tools: "Outils & Infrastructure",
    },
    projects: {
      title: "Projets",
      viewCode: "Voir",
      viewDemo: "Démo live",
      inProgress: "En cours",
      confidential: "",
    },
    services: {
      title: "Services",
      subtitle: "Ce que je construis pour vous",
      web: "Architecture Backend SaaS",
      webDesc:
        "APIs REST scalables, multi-tenancy, gestion des abonnements, logique métier complexe",
      ai: "Automatisation & Scraping",
      aiDesc:
        "Workflows n8n/Make, scraping Python/Node.js, extraction et structuration de données",
      data: "Data Engineering",
      dataDesc:
        "Pipelines de données, analyse, visualisation, modèles prédictifs avec Python",
      automation: "Intégration & APIs",
      automationDesc:
        "Intégrations tierces, WhatsApp API, paiements, notifications, webhooks",
    },
    blog: {
      title: "Blog & Articles",
      subtitle: "Prochainement",
      coming: "Bientôt disponible",
    },
    contact: {
      title: "Contact",
      subtitle: "Parlons de votre projet",
      location: "Abomey-Calavi, Bénin · Remote",
      name: "Nom",
      email: "Email",
      message: "Message",
      send: "Envoyer",
    },
    cv: {
      pageTitle: "Curriculum Vitae",
      download: "Télécharger PDF",
      role: "Architecte Backend · SaaS · Automatisation",
      tagline:
        "Je construis des infrastructures backend conçues pour la croissance — sécurité des données, optimisation des coûts serveur, architecture modulaire.",
      experience: "Expérience",
      projects: "Projets clés",
      education: "Formation",
      skills: "Compétences",
      languages: "Langues",
      certifications: "Certifications",
      contact: "Contact",
      available: "Disponible pour missions remote",
      backend: "Backend core",
      databases: "Bases de données",
      saas: "SaaS & Infra",
      automation: "Automatisation",
      frontend: "Frontend",
      fluent: "Courant",
      technical: "Technique",
      native: "Langue maternelle",
    },
  },

  en: {
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      projects: "Projects",
      services: "Services",
      blog: "Blog",
      contact: "Contact",
      cv: "My Resume",
    },
    hero: {
      badge: "Open to remote contracts",
      name: "Eldo-Moréo",
      title: "Backend Architect · SaaS · Automation",
      description:
        "I design robust, scalable backend systems to turn your product ideas into profitable solutions. Data security, server cost optimization, modular architecture — iterate fast without breaking everything.",
      cta1: "View Projects",
      cta2: "Contact Me",
      viewCV: "My Resume",
      downloadCV: "Download Resume",
      stat1label: "Years backend experience",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL in production",
      stat2label: "SaaS projects delivered",
      stat2sub: "Multi-tenancy, REST APIs, subscription systems",
      stat3label: "Remote · International",
      stat3sub: "Available West Africa & international",
    },
    about: {
      title: "About",
      intro:
        "Full-Stack Developer specialized in SaaS architecture and automation. I build backend infrastructures designed for growth.",
      values: "My Values",
      learning: "Continuous learning",
      learningDesc: "Always watching backend architecture trends and patterns",
      flexibility: "Pragmatism",
      flexibilityDesc:
        "Simple, maintainable solutions that hold up in production",
      patience: "Rigor",
      patienceDesc: "Methodical approach: architecture first, then code",
      travel: "Product vision",
      travelDesc: "I think business as much as technical",
    },
    skills: {
      title: "Technical Skills",
      dataScience: "Data & Automation",
      webDev: "Backend & Web Development",
      tools: "Tools & Infrastructure",
    },
    projects: {
      title: "Projects",
      viewCode: "View",
      viewDemo: "Live Demo",
      inProgress: "In Progress",
      confidential: "",
    },
    services: {
      title: "Services",
      subtitle: "What I build for you",
      web: "Backend SaaS Architecture",
      webDesc:
        "Scalable REST APIs, multi-tenancy, subscription management, complex business logic",
      ai: "Automation & Scraping",
      aiDesc:
        "n8n/Make workflows, Python/Node.js scraping, data extraction and structuring",
      data: "Data Engineering",
      dataDesc:
        "Data pipelines, analysis, visualization, predictive models with Python",
      automation: "Integration & APIs",
      automationDesc:
        "Third-party integrations, WhatsApp API, payments, notifications, webhooks",
    },
    blog: {
      title: "Blog & Articles",
      subtitle: "Coming soon",
      coming: "Coming Soon",
    },
    contact: {
      title: "Contact",
      subtitle: "Let's talk about your project",
      location: "Abomey-Calavi, Benin · Remote",
      name: "Name",
      email: "Email",
      message: "Message",
      send: "Send",
    },
    cv: {
      pageTitle: "Resume",
      download: "Download PDF",
      role: "Backend Architect · SaaS · Automation",
      tagline:
        "I build backend infrastructures designed for growth — data security, server cost optimization, modular architecture.",
      experience: "Experience",
      projects: "Key Projects",
      education: "Education",
      skills: "Skills",
      languages: "Languages",
      certifications: "Certifications",
      contact: "Contact",
      available: "Open to remote contracts",
      backend: "Backend core",
      databases: "Databases",
      saas: "SaaS & Infra",
      automation: "Automation",
      frontend: "Frontend",
      fluent: "Fluent",
      technical: "Technical",
      native: "Mother tongue",
    },
  },

  fon: {
    nav: {
      home: "Xwédo",
      about: "Wémè",
      skills: "Sɔsɔtɔ",
      projects: "Nɔ̀ Kɔ̀",
      services: "Dɔ̀dɔ̀",
      blog: "Blogo",
      contact: "Wɛ nú",
      cv: "CV Tɔn",
    },
    hero: {
      badge: "Mí nɔ́ dɔ remote",
      name: "Eldo-Moréo",
      title: "Backend Architect · SaaS · Automation",
      description:
        "Mí nɔ̀ hɛn backend tɔn lɛ wɛ dɛ kplɛ scalable do nɔ̀ kɔ̀ mí tɔn wɛ́ sɔ́ ɖe hùn nu nɔnso.",
      cta1: "Wá kɔ̀ mí nɔ̀",
      cta2: "Wɛ nú mí",
      viewCV: "CV Tɔn",
      downloadCV: "Tó CV",
      stat1label: "Xwé backend tɔn",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL",
      stat2label: "SaaS nɔ̀ kɔ̀",
      stat2sub: "Multi-tenancy, REST APIs",
      stat3label: "Remote · International",
      stat3sub: "Mí nɔ́ dɔ Bénin kplɛ international",
    },
    about: {
      title: "Wémè mí",
      intro: "Full-Stack Developer mí nɔ̀ SaaS kplɛ automation gbé.",
      values: "Wémɛ mí",
      learning: "Kɔ́ nú kpɔ́nsɔ",
      learningDesc: "Mí sɔ́ gbédodo nú jà sɔ́sɔtɔ",
      flexibility: "Wèwè",
      flexibilityDesc: "Mí kɔ́ yí do kplɔ́ nú tékínolojì tò",
      patience: "Wáyè",
      patienceDesc: "Mí sɔ́ sɔ́sɔtɔ gbé ɖe hùn nu nɔnso",
      travel: "Vision",
      travelDesc: "Mí gbé business kplɛ technique",
    },
    skills: {
      title: "Sɔsɔtɔ Teknik",
      dataScience: "Data & Automation",
      webDev: "Backend & Web",
      tools: "Outils",
    },
    projects: {
      title: "Nɔ̀ Kɔ̀",
      viewCode: "Wá kɔ̀",
      viewDemo: "Demo",
      inProgress: "Nɔ̀ ɖo",
      confidential: "",
    },
    services: {
      title: "Dɔ̀dɔ̀",
      subtitle: "Mí nɔ̀ hɛn ɖo",
      web: "Backend SaaS",
      webDesc: "APIs REST, multi-tenancy, subscription",
      ai: "Automation & Scraping",
      aiDesc: "n8n, Make, Python scraping",
      data: "Data Engineering",
      dataDesc: "Pipeline data, analyse, Python",
      automation: "Integration",
      automationDesc: "WhatsApp API, paiements, webhooks",
    },
    blog: { title: "Blog", subtitle: "Bientôt", coming: "Bientôt" },
    contact: {
      title: "Wɛ nú mí",
      subtitle: "Wá gbé mí nɔn do nɔ̀ ɖo",
      location: "Abomey-Calavi, Bénin",
      name: "Sɔ̀",
      email: "Email",
      message: "Nɔ̀nkpɔ̀",
      send: "Sɔ́",
    },
    cv: {
      pageTitle: "CV",
      download: "Tó PDF",
      role: "Backend Architect · SaaS · Automation",
      tagline: "Mí nɔ̀ hɛn backend tɔn lɛ wɛ dɛ kplɛ scalable.",
      experience: "Expérience",
      projects: "Projets",
      education: "Formation",
      skills: "Sɔsɔtɔ",
      languages: "Gbé",
      certifications: "Certifications",
      contact: "Wɛ nú",
      available: "Remote",
      backend: "Backend",
      databases: "BDD",
      saas: "SaaS",
      automation: "Automation",
      frontend: "Frontend",
      fluent: "Courant",
      technical: "Technique",
      native: "Gbé dɔ",
    },
  },

  es: {
    nav: {
      home: "Inicio",
      about: "Sobre mí",
      skills: "Habilidades",
      projects: "Proyectos",
      services: "Servicios",
      blog: "Blog",
      contact: "Contacto",
      cv: "Mi CV",
    },
    hero: {
      badge: "Disponible para proyectos remote",
      name: "Eldo-Moréo",
      title: "Arquitecto Backend · SaaS · Automatización",
      description:
        "Diseño sistemas backend robustos y escalables para convertir tus ideas de producto en soluciones rentables. Seguridad de datos, optimización de costos de servidor, arquitectura modular.",
      cta1: "Ver proyectos",
      cta2: "Contactarme",
      viewCV: "Mi CV",
      downloadCV: "Descargar CV",
      stat1label: "Años de experiencia backend",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL en producción",
      stat2label: "Proyectos SaaS entregados",
      stat2sub: "Multi-tenancy, REST APIs, sistemas de suscripción",
      stat3label: "Remote · Internacional",
      stat3sub: "Disponible África Occidental e internacional",
    },
    about: {
      title: "Sobre mí",
      intro:
        "Desarrollador Full-Stack especializado en arquitectura SaaS y automatización.",
      values: "Mis Valores",
      learning: "Aprendizaje continuo",
      learningDesc: "Siempre al tanto de arquitecturas y patrones backend",
      flexibility: "Pragmatismo",
      flexibilityDesc:
        "Soluciones simples, mantenibles, que funcionan en producción",
      patience: "Rigor",
      patienceDesc: "Enfoque metódico: arquitectura primero, código después",
      travel: "Visión de producto",
      travelDesc: "Pienso en negocio tanto como en técnica",
    },
    skills: {
      title: "Habilidades Técnicas",
      dataScience: "Data & Automatización",
      webDev: "Backend & Desarrollo Web",
      tools: "Herramientas & Infraestructura",
    },
    projects: {
      title: "Proyectos",
      viewCode: "Ver",
      viewDemo: "Demo en vivo",
      inProgress: "En progreso",
      confidential: "",
    },
    services: {
      title: "Servicios",
      subtitle: "Lo que construyo para ti",
      web: "Arquitectura Backend SaaS",
      webDesc: "APIs REST escalables, multi-tenancy, gestión de suscripciones",
      ai: "Automatización & Scraping",
      aiDesc: "Flujos n8n/Make, scraping Python/Node.js, extracción de datos",
      data: "Ingeniería de Datos",
      dataDesc: "Pipelines de datos, análisis, visualización con Python",
      automation: "Integración & APIs",
      automationDesc:
        "Integraciones de terceros, WhatsApp API, pagos, webhooks",
    },
    blog: { title: "Blog", subtitle: "Próximamente", coming: "Próximamente" },
    contact: {
      title: "Contacto",
      subtitle: "Hablemos de tu proyecto",
      location: "Abomey-Calavi, Benin · Remote",
      name: "Nombre",
      email: "Email",
      message: "Mensaje",
      send: "Enviar",
    },
    cv: {
      pageTitle: "Curriculum Vitae",
      download: "Descargar PDF",
      role: "Arquitecto Backend · SaaS · Automatización",
      tagline:
        "Construyo infraestructuras backend diseñadas para el crecimiento.",
      experience: "Experiencia",
      projects: "Proyectos clave",
      education: "Formación",
      skills: "Habilidades",
      languages: "Idiomas",
      certifications: "Certificaciones",
      contact: "Contacto",
      available: "Disponible remote",
      backend: "Backend core",
      databases: "Bases de datos",
      saas: "SaaS & Infra",
      automation: "Automatización",
      frontend: "Frontend",
      fluent: "Fluido",
      technical: "Técnico",
      native: "Lengua materna",
    },
  },

  de: {
    nav: {
      home: "Startseite",
      about: "Über mich",
      skills: "Fähigkeiten",
      projects: "Projekte",
      services: "Leistungen",
      blog: "Blog",
      contact: "Kontakt",
      cv: "Lebenslauf",
    },
    hero: {
      badge: "Verfügbar für Remote-Projekte",
      name: "Eldo-Moréo",
      title: "Backend-Architekt · SaaS · Automatisierung",
      description:
        "Ich entwerfe robuste, skalierbare Backend-Systeme, um Ihre Produktideen in rentable Lösungen zu verwandeln.",
      cta1: "Projekte ansehen",
      cta2: "Kontakt",
      viewCV: "Lebenslauf",
      downloadCV: "Lebenslauf herunterladen",
      stat1label: "Jahre Backend-Erfahrung",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL",
      stat2label: "SaaS-Projekte geliefert",
      stat2sub: "Multi-tenancy, REST APIs",
      stat3label: "Remote · International",
      stat3sub: "Verfügbar Westafrika & international",
    },
    about: {
      title: "Über mich",
      intro:
        "Full-Stack-Entwickler, spezialisiert auf SaaS-Architektur und Automatisierung.",
      values: "Meine Werte",
      learning: "Kontinuierliches Lernen",
      learningDesc: "Immer auf dem Laufenden bei Backend-Architektur",
      flexibility: "Pragmatismus",
      flexibilityDesc:
        "Einfache, wartbare Lösungen, die in der Produktion standhalten",
      patience: "Sorgfalt",
      patienceDesc: "Methodischer Ansatz: Architektur zuerst",
      travel: "Produktvision",
      travelDesc: "Ich denke genauso viel über Business wie über Technik nach",
    },
    skills: {
      title: "Technische Fähigkeiten",
      dataScience: "Data & Automatisierung",
      webDev: "Backend & Webentwicklung",
      tools: "Tools & Infrastruktur",
    },
    projects: {
      title: "Projekte",
      viewCode: "Ansehen",
      viewDemo: "Live Demo",
      inProgress: "In Bearbeitung",
      confidential: "",
    },
    services: {
      title: "Leistungen",
      subtitle: "Was ich für Sie baue",
      web: "Backend SaaS-Architektur",
      webDesc: "Skalierbare REST APIs, Multi-Tenancy, Abonnementverwaltung",
      ai: "Automatisierung & Scraping",
      aiDesc: "n8n/Make-Workflows, Python/Node.js-Scraping",
      data: "Data Engineering",
      dataDesc: "Datenpipelines, Analyse, Visualisierung mit Python",
      automation: "Integration & APIs",
      automationDesc: "Drittanbieter-Integrationen, WhatsApp API, Zahlungen",
    },
    blog: {
      title: "Blog",
      subtitle: "Bald verfügbar",
      coming: "Bald verfügbar",
    },
    contact: {
      title: "Kontakt",
      subtitle: "Sprechen wir über Ihr Projekt",
      location: "Abomey-Calavi, Benin · Remote",
      name: "Name",
      email: "Email",
      message: "Nachricht",
      send: "Senden",
    },
    cv: {
      pageTitle: "Lebenslauf",
      download: "PDF herunterladen",
      role: "Backend-Architekt · SaaS · Automatisierung",
      tagline: "Ich baue Backend-Infrastrukturen für Wachstum.",
      experience: "Erfahrung",
      projects: "Wichtige Projekte",
      education: "Ausbildung",
      skills: "Fähigkeiten",
      languages: "Sprachen",
      certifications: "Zertifizierungen",
      contact: "Kontakt",
      available: "Remote verfügbar",
      backend: "Backend",
      databases: "Datenbanken",
      saas: "SaaS & Infra",
      automation: "Automatisierung",
      frontend: "Frontend",
      fluent: "Fließend",
      technical: "Fachlich",
      native: "Muttersprache",
    },
  },

  yo: {
    nav: {
      home: "Ile",
      about: "Nipa mi",
      skills: "Ogbón",
      projects: "Àwọn iṣẹ́",
      services: "Ìṣẹ́",
      blog: "Búlóògì",
      contact: "Kan si mi",
      cv: "CV Mi",
    },
    hero: {
      badge: "Ṣetan fún iṣẹ́ latọ̀nà jìnnà",
      name: "Eldo-Moréo",
      title: "Ayáwò Backend · SaaS · Adaṣiṣẹ",
      description:
        "Mo ṣe àwọn ètò backend tó le àti tó le gbooro láti yí àwọn èrò ọja rẹ sí ojútùú tó níwọ̀n.",
      cta1: "Wo iṣẹ́ mi",
      cta2: "Kan sí mi",
      viewCV: "CV Mi",
      downloadCV: "Gba CV",
      stat1label: "Ọdún iriri backend",
      stat1sub: "NestJS, Node.js, Laravel, PostgreSQL",
      stat2label: "Àwọn iṣẹ́ SaaS tí a pé",
      stat2sub: "Multi-tenancy, REST APIs",
      stat3label: "Remote · Àgbáyé",
      stat3sub: "Ṣetan Ìwọ̀ Oòrùn Áfríkà & àgbáyé",
    },
    about: {
      title: "Nipa mi",
      intro: "Oníṣẹ́ Full-Stack tó ṣàpẹẹrẹ nínú ẹ̀rọ SaaS àti adaṣiṣẹ.",
      values: "Àwọn iye mi",
      learning: "Ìkẹ́kọọ̀ àìdádúró",
      learningDesc: "Máa ń tẹ̀lé àwọn ìṣẹ̀lẹ̀ backend",
      flexibility: "Ìmọ̀",
      flexibilityDesc: "Àwọn ojútùú rọrùn tó dúró nínú iṣẹ́",
      patience: "Ìṣọ́ra",
      patienceDesc: "Ìlànà ìmọ̀: ẹ̀rọ kọ́kọ́",
      travel: "Ìríran ọjà",
      travelDesc: "Mo ronú nípa iṣẹ́ ó sì wà pẹ̀lú ẹ̀rọ",
    },
    skills: {
      title: "Ogbón Àmúlò",
      dataScience: "Data & Adaṣiṣẹ",
      webDev: "Backend & Ìdàgbàsókè Wẹẹbù",
      tools: "Ohun èlò & Àwọn ẹ̀rọ",
    },
    projects: {
      title: "Àwọn iṣẹ́",
      viewCode: "Wo kóòdù",
      viewDemo: "Àpẹẹrẹ",
      inProgress: "Nínú ilọsiwaju",
      confidential: "",
    },
    services: {
      title: "Àwọn ìṣẹ́",
      subtitle: "Ohun tí mo kọ́ fún ọ",
      web: "Ẹ̀rọ Backend SaaS",
      webDesc: "REST APIs tó le gbooro, multi-tenancy, ìṣàkóso ìforúkọsilẹ̀",
      ai: "Adaṣiṣẹ & Scraping",
      aiDesc: "Àwọn ìtọ́sọ́nà n8n/Make, scraping Python/Node.js",
      data: "Ẹ̀rọ Data",
      dataDesc: "Àwọn ọ̀nà data, ìtúpalẹ̀, Python",
      automation: "Ìṣọ̀kan & APIs",
      automationDesc: "Àwọn ìṣọ̀kan kẹta, WhatsApp API, ìsanwó",
    },
    blog: { title: "Búlóògì", subtitle: "Ní pípẹ́", coming: "Ní pípẹ́" },
    contact: {
      title: "Kan si mi",
      subtitle: "Jẹ́ ká sọ̀rọ̀ nípa iṣẹ́ rẹ",
      location: "Abomey-Calavi, Benin · Remote",
      name: "Orúkọ",
      email: "Email",
      message: "Ìfiránṣẹ́",
      send: "Fi ranṣẹ́",
    },
    cv: {
      pageTitle: "CV",
      download: "Gba PDF",
      role: "Ayáwò Backend · SaaS · Adaṣiṣẹ",
      tagline: "Mo kọ́ àwọn ẹ̀rọ backend fún ìdàgbàsókè.",
      experience: "Iriri",
      projects: "Àwọn iṣẹ́ pàtàkì",
      education: "Ìkẹ́kọọ̀",
      skills: "Ogbón",
      languages: "Àwọn èdè",
      certifications: "Àwọn ìdánilójú",
      contact: "Kan si mi",
      available: "Ṣetan fún remote",
      backend: "Backend",
      databases: "Àkójọ data",
      saas: "SaaS & Infra",
      automation: "Adaṣiṣẹ",
      frontend: "Frontend",
      fluent: "Gíga",
      technical: "Ìmọ̀-ẹrọ",
      native: "Èdè ìbí",
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("fr");
  const currentTranslations = {
    ...translations.fr,
    ...(translations[language] || {}),
  };
  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t: currentTranslations }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context)
    throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
